_BASE_: Base-ADE20KFull-847.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "ZegFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 65535
    NUM_CLASSES: 847
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    TRAIN_CLASS_JSON: "datasets/ADE20K_2021_17_01/ADE20K_572_pure_class.json"
    TEST_CLASS_JSON: "datasets/ADE20K_2021_17_01/ADE20K_847_pure_class.json"
    CLIP_PRETRAINED: "ViT-B/16"
    CLIP_CLASSIFICATION: True
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
    GZERO_CALIBRATE: 0.0
#    ENSEMBLING_ALL_CLS: True
    ENSEMBLING: True
  PROMPT_ENSEMBLE_TYPE: "imagenet_select"
#  PROMPT_ENSEMBLE_TYPE: "single"
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 32
#  IMS_PER_BATCH: 8
  MAX_ITER: 60000
DATASETS:
  TRAIN: ("ade20k_full_sem_seg_freq_train",)
  TEST: ("ade20k_full_sem_seg_freq_val_all",)
DATALOADER:
  NUM_WORKERS: 8
CUDNN_BENCHMARK: True
